DROP TABLE IF EXISTS USERS, FRIENDS, FILMS, LIKES, FILM_GENRES, GENRES, MPA;

CREATE TABLE IF NOT EXISTS USERS (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(50) NOT NULL,
    name varchar(50),
    birthday date,
    email varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    user_id bigint REFERENCES USERS (user_id),
    friend_id bigint REFERENCES USERS (user_id)
);

CREATE TABLE IF NOT EXISTS MPA (
    mpa_id int PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS FILMS (
    film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200) NOT NULL,
    releaseDate date NOT NULL,
    duration int,
    mpa_id int REFERENCES MPA (mpa_id)
);

CREATE TABLE IF NOT EXISTS LIKES (
    film_id bigint REFERENCES FILMS (film_id),
    user_id bigint REFERENCES USERS (user_id)
);

CREATE TABLE IF NOT EXISTS GENRES (
    genre_id int PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
    film_id bigint REFERENCES FILMS (film_id),
    genre_id int REFERENCES GENRES (genre_id)
);